docs/populating-configuration.md

remove keycloak cert part from populating configuration docs

---

.gitleaks.toml

- ~~[ ] All acceptance criteria specified in JIRA have been completed~~
- ~~[ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)~~~
- ~~[ ] Documentation added for the feature~~
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] Verified independently by reviewer~~
- ~~[ ] Required metrics/dashboards/alerts have been added (or PR created).~~
- ~~[ ] Required Standard Operating Procedure (SOP) is added.~~
- ~~[ ] JIRA has created for changes required on the client side~~

chore: setup gitleaks allowlist

---

docker/Dockerfile_template
docker/Dockerfile_template_mocked

chore: download latest version of ocm in midstream CI templates

---

docs/populating-configuration.md

Add external_id retrieval info to populating-configuration.md

docs: Add external_id retrieval info to populating-configuration.md

---

.gitleaks.toml

chore: Add test jwt private key to gitleaks allowlist

---

README.md

* Always use same number for lists so not numbering rewriting is needed when moving list elements
* Reword a few sentences
* Add some minor sentences

Minor README.md changes 1

---

README.md
docs/populating-configuration.md

Adds information about
* How to interact with OCM
* Retrieve and generate OCM offline tokens and OCM tokens
* How to perform authenticated requests to the Fleet Manager API using OCM tokens
* How to setup Fleet Manager to be able to interact with OCM

docs: Add OCM interaction information

---

docs/populating-configuration.md

* Extends the documentation around setting up a custom TLS certificate for Dinosaur instances' Host URLs in Fleet Manager

docs: extend dinosaur custom tls configuration doc

---

docs/populating-configuration.md

* Extends the documentation around setting up Fleet Manager to interact with AWS

docs: Extend aws configuration docs

---

docs/populating-configuration.md
docs/quota-management-list-configuration.md

* Modifies the populating configuration document organization
* Expands and reorganizes the documentation about standard instances creation in the populating configuration document

docs: reorg of populating config and expand standard instances doc

---

README.md

docs: minor changes to README

---

CONTRIBUTING.md

docs(contributing): add updates proposal

---

Makefile
README.md
docs/feature-flags.md
docs/populating-configuration.md
docs/quota-management-list-configuration.md

- Expand the populating configuration docs with
the fleet manager dependencies and give context
about them
- Rework the main README

docs: documentation improvements

---

internal/dinosaur/internal/workers/clusters_mgr.go

This allows volume size override and works with OpenShift 4.1
- ~~[ ] All acceptance criteria specified in JIRA have been completed~~
- ~~[ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)~~
- ~~[ ] Documentation added for the feature~~
- ~~[ ] Required metrics/dashboards/alerts have been added (or PR created).~~
- ~~[ ] Required Standard Operating Procedure (SOP) is added.~~
- ~~[ ] JIRA has created for changes required on the client side~~

chore(observability): update to v3.0.9

---

internal/dinosaur/internal/handlers/authentication.go
internal/dinosaur/internal/routes/route_loader.go
internal/dinosaur/routes/constants.go
pkg/server/server_config.go
templates/service-template.yml

This allows for dynamic configuration of these variables
Related to https://github.com/bf2fc6cc711aee1a0c2a/ffm-project/issues/8#issuecomment-1040724175

feat(server-config): expose base path and api version as server config

---

docs/the-fleetshard-pattern.md

Fixes https://github.com/bf2fc6cc711aee1a0c2a/ffm-project/issues/14

docs(fleetshard): add links to fleetshard pattern

---

internal/dinosaur/constants/cluster.go
internal/dinosaur/internal/api/dbapi/dinosaur_request_types.go
internal/dinosaur/internal/config/dataplane_cluster_config.go
internal/dinosaur/internal/workers/clusters_mgr.go
internal/dinosaur/test/integration/auth_test.go
pkg/auth/helper.go
pkg/client/observatorium/observability_config.go
pkg/client/ocm/types.go
pkg/constants/operators.go
pkg/db/connection.go
pkg/errors/errors.go
pkg/logger/logger.go
pkg/quota_management/quota_management_list_config.go
pkg/services/sentry/sentry.go
test/helper.go

Also centralise some constants in the constants directory

refactor: remove a bunch of TODO that are not meant to be replaced by the user

---

CONTRIBUTING.md
DCO
LICENSE

* Add Apache License 2.0
* Add DCO (Developer Certificate of Origin)
* Update CONTRIBUTING.md to reference the new legal related information
Related to https://issues.redhat.com/browse/MGDSTRM-7442

Add legal related content

---

docs/observability/README.md
docs/populating-configuration.md

* Extend observability populating doc
* Minor formatting changes

docs: extend observability populating doc

---

internal/dinosaur/internal/handlers/dinosaur.go
internal/dinosaur/internal/handlers/validation.go

fix: bring dinosaur owner check

---

pkg/db/logger.go

Apply https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/949 patch!

fix(db): ensure enable-db-debug is honored and prints SQL statements

---

go.mod
go.sum
pkg/server/api_server.go

backport of https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1154
None, needed. Once https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1154 is merged, we can merge this one.

build(deps): remove the github.com/dgrijalva/jwt-go package

---

internal/dinosaur/constants/dinosaur.go

follows up https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1345

refactor: remove unused constant

---

docs/getting-credentials-and-accounts.md

Being that specific is not needed in the repository being public and potentially applying to external contributors / audiences.

chore: remove specific aws account request contact information
